---
title: "An overview of the different type of graphics"
author: "Christophe Bontemps (UN SIAP)"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    code_folding: show
    highlight: tango
    number_sections: yes
    theme: lumen
  html_notebook: default
  pdf_document: default
---


```{r setup, include=FALSE}
knitr::opts_chunk$set( message = FALSE, warning = FALSE, results =FALSE, echo = TRUE) 

```

```{r}
# My colors:
SIAP.color <- "#0385a8"

```

```{r}
library(readxl)
library(tidyverse)
library(viridis)
library(ggthemes)
library(ggplot2)
library(forcats)
library(knitr)
library(kableExtra)

```

## Data sets

```{r, SDGData}

# ---  SDGs Data --- 
SDGdata<- readxl::read_xlsx("Data/SDGDataSample.xlsx", col_names = TRUE, sheet = "Goal1")

SDGdata$Poverty <- as.numeric(SDGdata$Value)
MyDataPov <- subset(SDGdata, Poverty >5 & Sex =="BOTHSEX" )
MyDataPov.caption <- paste("Proportion of population below international
                           poverty line (%)- Obs. 1-9/", nrow(MyDataPov))
```


```{r table}
 t <-  kbl(MyDataPov[1:9,
                     c("Indicator","Age", "Poverty", "TimePeriod" )],
           caption = MyDataPov.caption
)  

kable_styling(t)
```




# Univariate numerical data

```{r}
ggplot(data= MyDataPov) +
 aes(x = Poverty, y ="") +
    geom_point(color=SIAP.color, size=0.9, alpha=0.9) +
   ggtitle("Points (raw values)")+ 
  xlab(MyDataPov.caption)+
 theme_tufte()

```

```{r rug}
ggplot(data= subset(SDGdata, Poverty >5 & Sex =="BOTHSEX" )) +
 aes(x = Poverty) +
    geom_rug(color=SIAP.color, size=0.9, alpha=0.7) +
   ggtitle("Rug plot")+ 
  xlab(MyDataPov.caption)+
 theme_tufte()

```


```{r jitter }
ggplot(data= MyDataPov) +
 aes(x = Poverty, y ="") +
    geom_jitter(color=SIAP.color, size=0.9, alpha=0.9, width = 0.2 ) +
   ggtitle("Points (jitter)")+ 
  xlab(MyDataPov.caption)+
 theme_tufte()

```


```{r boxplot}
ggplot(data= MyDataPov) +
 aes(x = Poverty) +
    geom_boxplot( fill=SIAP.color,color=SIAP.color, alpha=0.2) +
  ggtitle("Boxplot (Box-and-Whiskers")+ 
  xlab(MyDataPov.caption)+
 theme_tufte()
```


```{r}
ggplot(data= MyDataPov) +
 aes(x = Poverty, y ="") +
    geom_boxplot(fill=SIAP.color,color=SIAP.color, alpha=0.2) +
    geom_jitter(color=SIAP.color, size=0.9, alpha=0.9, width = 0.2 ) +
   ggtitle("Boxplot and points (jittered)")+ 
  xlab(MyDataPov.caption)+
 theme_tufte()

```

```{r histogram}
ggplot(data= MyDataPov) +
 aes(x = Poverty) +
 geom_histogram(bins = 39L, fill = SIAP.color) +
   ggtitle("Histogram")+ 
  xlab(MyDataPov.caption)+
 theme_tufte()
```


```{r density }
ggplot(data= MyDataPov) +
 aes(x = Poverty) +
    geom_density( fill=SIAP.color,color=SIAP.color, alpha=0.2) +
   ggtitle("Density estimate")+ 
  xlab(MyDataPov.caption)+
 theme_tufte()

```

```{r densityrug}
ggplot(data= MyDataPov) +
 aes(x = Poverty) +
    geom_density( fill=SIAP.color,color=SIAP.color, alpha=0.2) +
    geom_rug(color=SIAP.color, size=0.9, alpha=0.7) +
   ggtitle("Density estimate + rug")+ 
  xlab(MyDataPov.caption)+
 theme_tufte()

```



# Univariate numerical data by categories (ordered or not)

```{r}
SDGdata %>%
 filter(Sex %in% c("MALE", "FEMALE")) %>%
 ggplot() +
 aes(x = "", y = Poverty, group = Sex) +
 geom_boxplot(fill = "#0c4c8a") +
 #labs(x = "Countries", y = "Pove", caption = "only....") +
  coord_flip()+
 theme_minimal()
```





```{r}
# create a dataset
data <- data.frame(
  name=c( rep("A",500), rep("B",500), rep("B",500), rep("C",20), rep('D', 100)  ),
  value=c( rnorm(500, 10, 5), rnorm(500, 13, 1), rnorm(500, 18, 1), rnorm(20, 25, 4), rnorm(100, 12, 1) )
)

# Plot
data %>%
  ggplot( aes(x=name, y=value, fill=name)) +
  geom_boxplot() +
  scale_fill_viridis(discrete = TRUE, alpha=0.6) +
  geom_jitter(color="black", size=0.4, alpha=0.9) +
  theme(
    legend.position="none",
    plot.title = element_text(size=11)
  ) +
  theme_minimal()+
  ggtitle("A boxplot with jitter") +
  xlab("")

```



```{r}
# library
library(ggridges)

# Diamonds dataset is provided by R natively
#head(diamonds)

# basic example
ggplot(diamonds, aes(x = price, y = cut, fill = cut)) +
  geom_density_ridges() +
  theme_ridges() + 
  theme(legend.position = "none")
```


```{r}

# Load dataset from github
data <- read.table("https://raw.githubusercontent.com/zonination/perceptions/master/probly.csv", header=TRUE, sep=",")
data <- data %>% 
  gather(key="text", value="value") %>%
  mutate(text = gsub("\\.", " ",text)) %>%
  mutate(value = round(as.numeric(value),0)) %>%
  filter(text %in% c("Almost Certainly","Very Good Chance","We Believe","Likely","About Even", "Little Chance", "Chances Are Slight", "Almost No Chance"))

# Plot
data %>%
  mutate(text = fct_reorder(text, value)) %>%
  ggplot( aes(y=text, x=value,  fill=text)) +
  geom_density_ridges(alpha=0.6, stat="binline", bins=20) +
  theme_ridges() +
  theme(
    legend.position="none",
    panel.spacing = unit(0.1, "lines"),
    strip.text.x = element_text(size = 8)
  ) +
  xlab("") +
  ylab("Assigned Probability (%)")


```


# Univariate numerical data with an categorical order

```{r}
library(ggridges)
library(ggplot2)
library(viridis)


# Plot
ggplot(lincoln_weather, aes(x = `Mean Temperature [F]`, y = `Month`, fill = ..x..)) +
  geom_density_ridges_gradient(scale = 3, rel_min_height = 0.01) +
  scale_fill_viridis(name = "Temp. [F]", option = "C") +
  labs(title = 'Temperatures in Lincoln NE in 2016') +
  #theme_ipsum() +
    theme(
      legend.position="none",
      panel.spacing = unit(0.1, "lines"),
      strip.text.x = element_text(size = 8)
    )
```

