---
title: "SDG data importation and exportation for data visualization course"
author: "Christophe Bontemps (UN SIAP)"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document: 
    keep_tex: yes  ## keep images in folder + latex
  html_notebook: default
  html_document:
    code_folding: show
    highlight: tango
    number_sections: yes
    theme: lumen
---


```{r setup, include=FALSE}
# Remeber to disable png for Word export...
knitr::opts_chunk$set( message = FALSE, warning = FALSE, 
                       results =FALSE, echo = FALSE,
                       dev="png", 
                       dev.args=list(type="cairo"), dpi=96)

# My colors:
SIAP.color <- "#0385a8"

# Function used to recreate ggplot standard colors
ggplotColours <- function(n = 6, h = c(0, 360) + 15){
  if ((diff(h) %% 360) < 1) h[2] <- h[2] - 360/n
  hcl(h = (seq(h[1], h[2], length = n)), c = 100, l = 65)
}

```

```{r libraries}
library(readxl)
library(tidyverse)
library(viridis)
library(ggthemes)
library(ggplot2)
library(forcats)
library(knitr)
library(kableExtra)

```

## Data sets {-}

```{r SDGData}
# ---  SDGs Data --- 

# Data extracted from  https://unstats.un.org/SDGS/Indicators/Database/?area=TTO
# Only countries with letters A-C selected to avoid uneccessary heavy file

# Poverty index  (Goal 1.1.1)  Proportion of population below poverty line
SDGdata1<- readxl::read_xlsx("Data/SDGDataSample.xlsx", 
                             col_names = TRUE, sheet = "Goal1")

SDGdata1$Poverty <- as.numeric(SDGdata1$Value)

# Select only a portion of the data
SDGPov <- subset(SDGdata1, Poverty >5 & Sex =="BOTHSEX" )
SDGPov.caption <- "Indicator 1.1.1 (Prop. of pop. below international poverty line)"


# Child Mortality (Goal 3.2.1)
SDGdata3.2<- readxl::read_xlsx("Data/SDGDataSample.xlsx", 
                             col_names = TRUE, sheet = "Goal3-2-1")

SDGdata3.2$ChildDeath <- as.numeric(SDGdata3.2$Value)

# Select only a portion of the data
SDGChildDeath <- subset(SDGdata3.2, ChildDeath >1 & Sex =="BOTHSEX" )
SDGChildDeath.caption <- SDGdata3.2$SeriesDescription[1]
```

# Povery data set

```{r TableFull, echo = FALSE, results=TRUE}
 t <-  kbl(SDGPov[1:9,
                     c("Indicator","Age", "Poverty" ,"GeoAreaName")],
           caption = SDGPov.caption
)  

kable_styling(t,full_width = F)

# For interactive view of recording 
# View(SDGPov[c("Indicator","Age", "Poverty" )])
```


```{r SDGDataMaternal}
# ---  SDGs Data --- 
SDGdata3<- readxl::read_xlsx("Data/SDGDataSample.xlsx", col_names = TRUE,
                             sheet = "Goal3")

SDGdata3$Maternal <- as.numeric(SDGdata3$Value)

SDGMatPov <- merge(SDGdata3, SDGPov, by = c("GeoAreaName", "TimePeriod" ))

# Creating and Age variable

SDGMatPov <- SDGMatPov %>%
  mutate( Age = str_sub(Age.y, 1,2),  #Take the lower bound of the interval
          Age = as.numeric(Age)
  )


Maternal.label.full <- SDGdata3$SeriesDescription[1]
Maternal.label <- "Maternal Mortality Indic. (3.1.1)"
Poverty.label.full <- SDGPov$SeriesDescription[1]
Poverty.label <- "Poverty Indic. (1.1.1)"
```

## Summary of data set used for ggplot Tutorial (Module 4)

```{r SDGPovertyMaternal}
## Data used for GGPLOT tutorial
write.table(SDGMatPov, file ="Data/DG-Example-M4.csv")

t <-  kbl(SDGMatPov[1:9,
                     c("Maternal", "Age" , "Poverty" ,"GeoAreaName", "TimePeriod")],
           caption = SDGPov.caption
)  

kable_styling(t,full_width = F)


```





## Visualizing over time

> The goal is to see an evolution....

```{r, results= "asis"}
SDGMatPov.Time <- SDGMatPov %>%
  filter(GeoAreaName=="Brazil") %>%
  group_by(TimePeriod) %>%
  summarize(
    MatYear = mean(Maternal),
    PovYear = mean(Poverty)
  )
print(SDGMatPov.Time)
# library(xtable)
# xtable(SDGMatPov.Time)
```


```{r Lineplot}
ggplot(SDGMatPov.Time, aes(x=TimePeriod, y= PovYear)) +
#ggplot(toto, aes(x=TimePeriod, y= Poverty)) +
  geom_line(color = SIAP.color, alpha = 0.5, size = 1.5) +
  ggtitle("Line plot ") +
  xlab("Time")+
  ylab(Poverty.label)+
   theme_minimal()
```


```{r Connectedline}
ggplot(SDGMatPov.Time, aes(x=TimePeriod, y= PovYear)) +
  geom_line(color = SIAP.color, alpha = 0.5, size =1.2) +
  geom_point(color = SIAP.color, alpha = 0.5, size = 3)+
  ggtitle("Connected Line plot ") +
  xlab("Time")+
  ylab(Poverty.label)+
       theme_minimal()
```

```{r Area}
# geom_area start at 0, so we use  geom_ribbon (with ymax in the aes)
ggplot(SDGMatPov.Time, aes(x=TimePeriod, ymax= PovYear)) +
  geom_line(aes(x=TimePeriod, y= PovYear), color = SIAP.color, size =1.2) +
  geom_ribbon(aes(ymin = 5.2), fill = SIAP.color, alpha = 0.3) +  
  geom_point(aes(x=TimePeriod, y= PovYear),color = SIAP.color, 
             alpha = 0.5, size = 2)+
  ggtitle("Area plot ") +
  xlab("Time")+
#  ylim(5.5, NA)+
  ylab(Poverty.label)+
       theme_minimal()
```

## Visualiszing over time and categories 

```{r datatime}
# create data
set.seed(2512)
time <- as.numeric(rep(seq(from = 2000,to = 2006, by=1), each=6) ) # x Axis
value <- runif(42, 10, 30)               # y Axis
country <- paste("Country", rep(LETTERS[1:6],times=7))# group, one shape per group
MyDataTime <- data.frame(time, value, country)
write.table(MyDataTime, "Data/MydataTime.csv")

print(MyDataTime %>% arrange(country,time)  %>% relocate(country, time))

#library(xtable)

#xtable(MyDataTime %>% arrange(country,time)  %>% relocate(country, time))
```


```{r Spaghetti}
# Spaghetti plot
ggplot(MyDataTime, aes(x=time, y=value, group=country, color = country)) + 
    geom_line() +
    ggtitle("Spaghetti plot ") +
    labs(caption = "Generated Data") +
    xlab("Time")+
    ylim(c(0, 40)) +
    ylab("Population below poverty line (millions)")+
    theme_minimal() +
  theme(
  plot.caption = element_text(color = "grey", face = "italic"))
```


```{r Spaghetti2}
# Spaghetti plot
ggplot(MyDataTime, aes(x=time, y=value, group=country, color = country)) + 
    geom_line() +
    ggtitle("Spaghetti plot ") +
    labs(caption = "Generated Data") +
    xlab("Time")+
    ylim(c(0, 40)) +
    ylab("Population below poverty line (millions)")+
    theme_minimal() +
  theme(
  plot.caption = element_text(color = "grey", face = "italic"),
  legend.position="none")
```


```{r SpagettiGrey}

MyDataTime$country2 <- MyDataTime$country

ggplot(MyDataTime, aes(x=time, y=value, group=country)) +
    geom_line(color="grey") +
    geom_line(data = subset(MyDataTime, country == "Country A"),
              aes(color = SIAP.color)) +
    ggtitle("Spaghetti plot with one country highlighted ") +
    labs(caption = "Generated Data") +
    xlab("Time")+
    ylim(c(0, 40)) +
    ylab("Population below poverty line (millions)")+
    theme_minimal() +
  theme(
  plot.caption = element_text(color = "grey", face = "italic"), 
  legend.position="none",
  panel.grid = element_blank()
  )

```


## Small multiples 

```{r LineFacet}
ggplot(MyDataTime, aes(x=time, y=value, group=country, color = country)) + 
    geom_line() +
    facet_wrap(~country)+
    ggtitle("Multiple line plot ") +
    labs(caption = "Generated Data") +
    xlab("Time")+
    ylim(c(0, 50)) +
    ylab("Pop. below poverty line (millions)")+
    theme_minimal() +
  theme(
  plot.caption = element_text(color = "grey", face = "italic"), 
  legend.position="none")

```

```{r LineFacetGrey}

MyDataTime$country2 <- MyDataTime$country

ggplot(MyDataTime, aes(x=time, y=value)) + 
    geom_line(data = MyDataTime %>% dplyr::select(-country),
              aes(group=country2), 
              color="grey", size=0.5, alpha=0.7) +
    geom_line( aes(color=name), color=SIAP.color, size=1.2 )+
    facet_wrap(~country)+
    ggtitle("Multiple line plot ") +
    labs(caption = "Generated Data") +
    xlab("Time")+
    ylim(c(0, 50)) +
    ylab("Pop. below poverty line (millions)")+
    theme_minimal() +
  theme(
  plot.caption = element_text(color = "grey", face = "italic"), 
  legend.position="none",
  panel.grid = element_blank()
  )

```

## Multiple area plot 

```{r AreaFacet}
ggplot(MyDataTime, aes(x=time, y=value, group=country, fill = country)) + 
    geom_area(alpha = 0.8) +
    facet_wrap(~country)+
    ggtitle("Multiple area plot ") +
    labs(caption = "Generated Data") +
    xlab("Time")+
    ylim(c(0, 50)) +
    ylab("Pop. below poverty line (millions)")+
    theme_minimal() +
  theme(
  plot.caption = element_text(color = "grey", face = "italic"), 
  legend.position="none")

```

## Stacked area chart

> These charts are for specific data types 

```{r StackedArea}


# stacked area chart
ggplot(MyDataTime, aes(x=time, y=value, fill=country)) + 
    geom_area(alpha=0.6 , size=.5, colour="white") +
    ggtitle("Stacked Area plot ") +
    labs(caption = "Generated Data") +
    xlab("Time")+
    ylab("Population below poverty line ")+
    theme_minimal() +
  theme(
  plot.caption = element_text(color = "grey", face = "italic"), 
  legend.position = "bottom")
```

