---
title: "Visual Tables"
subtitle: "Tables vs Graphics? "
author: "Christophe Bontemps (UN SIAP)"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    code_folding: show
    highlight: tango
    number_sections: yes
    theme: lumen
  html_notebook: default
  pdf_document: 
    keep_tex: yes  ## keep images in folder + latex
---
```{r setup, include=FALSE}
# Remebmer to disable png for Word export...
knitr::opts_chunk$set( message = FALSE, warning = FALSE, 
                       results =FALSE, echo = FALSE,
                       dev="png", 
                       dev.args=list(type="cairo"), dpi=96)

# My colors:
SIAP.color <- "#0385a8"

```


```{r libraries}
library(readxl)
library(tidyverse)
library(viridis)
library(ggthemes)
library(ggplot2)
library(forcats)
library(knitr)
library(kableExtra)

```

## Data sets {-}

```{r SDGData}

# ---  SDGs Data --- 

# Data extracted from  https://unstats.un.org/SDGS/Indicators/Database/?area=TTO
# Only countries with letters A-C selected to avoid uneccessary heavy file

# Poverty index  (Goal 1.1.1)  Proportion of population below poverty line
SDGdata1<- readxl::read_xlsx("Data/SDGDataSample.xlsx", 
                             col_names = TRUE, sheet = "Goal1")

SDGdata1$Poverty <- as.numeric(SDGdata1$Value)

# Select only a portion of the data
SDGPov <- subset(SDGdata1, Poverty >5 & Sex =="BOTHSEX" )
SDGPov.caption <- "Indicator 1.1.1 (Prop. of pop. below international poverty line)"


# Child Mortality (Goal 3.2.1)
SDGdata3.2<- readxl::read_xlsx("Data/SDGDataSample.xlsx", 
                             col_names = TRUE, sheet = "Goal3-2-1")

SDGdata3.2$ChildDeath <- as.numeric(SDGdata3.2$Value)

# Select only a portion of the data
SDGChildDeath <- subset(SDGdata3.2, ChildDeath >1 & Sex =="BOTHSEX" )
SDGChildDeath.caption <- SDGdata3.2$SeriesDescription[1]


# --- Here we generate a dataset with categorical values 
#  Data set with age recorded by country
set.seed(2512)
MyDataNumCat <- data.frame(
  Country=c( rep("A",500), rep("B",500), rep("B",500), rep("C",20), rep('D', 100)  ),
  Age=c( rnorm(500, 20, 5), rnorm(500, 13, 1), rnorm(500, 18, 1), rnorm(20, 25, 4), rnorm(100, 12, 1) )
)

#  Avg by Country (category)
MyDataNumCatAvg <- MyDataNumCat %>%
  group_by(Country) %>%
  summarize(
    Age.Avg = mean(Age)
  )

```

## Data

```{r SDGMaternal}
# ---  SDGs Data --- 
SDGdata3<- readxl::read_xlsx("Data/SDGDataSample.xlsx", col_names = TRUE,
                             sheet = "Goal3")

SDGdata3$Maternal <- as.numeric(SDGdata3$Value)
```
 ## Filtering coutries with enough values
```{r}
SDGdata3.refined <- SDGdata3 %>%
  group_by(GeoAreaName) %>%
  mutate(
    NbYears = length(unique(TimePeriod))) %>%
  filter(NbYears == 18) %>%
  select(TimePeriod, GeoAreaName, Maternal)
```

```{r}
SDGMat.Time <- SDGdata3.refined %>%
  group_by(TimePeriod, GeoAreaName) %>%
  summarize(
    MatYear = mean(Maternal)
  )
print(SDGMat.Time)
```

## Tidy data

```{r}
library(tidyr)

# The arguments to spread():
# - data: Data object
# - key: Name of column containing the new column names
# - value: Name of column containing values
data_wide <- spread(SDGMat.Time, key = TimePeriod, value = MatYear)
data_wide

# Export
write_csv(data_wide, "Data/SDG3Wide.csv",col_names = TRUE)


```

```{r Sparktable, echo=TRUE, results= TRUE}
# From https://cranky-chandrasekhar-cfefcd.netlify.app/

library(sparkline)
library(kableExtra)
sparkline(0)


Spark <- SDGMat.Time %>%
  mutate(year = factor(TimePeriod)) %>%
  spread(year,  MatYear, fill = 1) %>%
  gather(year, MatYear, -GeoAreaName) %>%
  group_nest(GeoAreaName) %>%
  mutate(n = map(data, ~sum(.x$MatYear)),
         data = map(data, ~spk_chr(.x$MatYear))) %>%
  unnest() %>%
  arrange(desc(n)) %>%
  slice(1:200)



kable(Spark, escape = F, caption = "Table with names") %>%
  kable_styling(full_width = F) 
```

## Sparklines in base graphics with plotSparklineTable
This uses plotSparklineTable function from epanetReader package by Bradley Eck. This compact solution requires data to be in long table format and it has a limited customisation options. Great for making a rapid summaries with sparklines.

```{r}

library(epanetReader)
pdf("sparklines_base_epanetReader.pdf", height=6, width=10)
library(reshape)
library(RCurl)
dd <- read.csv(text = getURL("https://gist.githubusercontent.com/GeekOnAcid/da022affd36310c96cd4/raw/9c2ac2b033979fcf14a8d9b2e3e390a4bcc6f0e3/us_nr_of_crimes_1960_2014.csv"))
 d <- melt(dd[,c(2:11)])

pdf("sparklines_base_epanetReader.pdf", height=6, width=10)
Spark <- plotSparklineTable(d, row.var = 'variable', col.vars = 'value')


# d <- SDGdata3.refined %>%
#   mutate(Country = as.factor(GeoAreaName)) %>%
#   select(Country, Maternal)
# 
# pdf("sparklines_base_epanetReader.pdf", height=6, width=10)
# plotSparklineTable(d[,2:3], row.var = "Country", col.vars = "Maternal")
```

